name: Deploy homepage with SSH

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout project
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@d4b9b8ff72958532804b70bbe600ad43b36d5f2e # v.0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy project
        run: |
          rsync -aiv --exclude-from=exclude.txt ./ ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/var/www/html/v1/
